Sutton spr23
petschekr/Detachment-165 pull request #70
Opened 2024-04-01 18:35 UTC by JonahTS

Changed Cadre Info/Pictures , changed join date to Spring 2025. Waiting to receive updated NSE packets but cadre wants to go ahead and get the pictures changed.

2024-04-01 19:29 UTC, petschekr requested changes
Super minor stuff

2024-04-01 19:29 UTC, petschekr commented on content/contact.hbs
> +<<<<<<< HEAD
I think you have a leftover merge conflict here

2024-04-01 19:29 UTC, petschekr commented on content/join.hbs
> +					<p>To enroll for Spring 2025, please first review the <a href="files/Enrollment Information Packet_Spring 2023.pdf">Enrollment Information Packet</a>. Then, download and complete the GT New Stud
Make sure the file URL matches what's in `rendered/files`. I think this should be `files/Enrollment Information Packet Spring 2024.pdf`

2024-04-01 19:29 UTC, petschekr commented on content/join.hbs
> +					<p>To enroll for Spring 2025, please first review the <a href="files/Enrollment Information Packet_Spring 2023.pdf">Enrollment Information Packet</a>. Then, download the Crosstown New Student En
Same here

2024-04-01 19:29 UTC, petschekr commented on content/join.hbs
> +<<<<<<< HEAD
Another merge conflict that got left over. I think you want to keep the `<h1>Join in <span class="semester-text">Spring 2025</span> or later</h1>` and delete the rest

2024-04-03 20:54 UTC, JonahTS commented
Okay, I pushed it again, I think I fixed the merge conflicts

2024-04-04 20:04 UTC, petschekr requested changes

2024-04-04 20:04 UTC, petschekr commented on content/join.hbs
> +			<h1>Join in the <span class="semester-text">Spring 2025</span> semester</h1>
I think this should be Fall 2024 since it's for the upcoming semester

2024-04-04 20:04 UTC, petschekr commented on content/join.hbs
> +					<p>To enroll for Spring 2025, please first review the <a href="files/Enrollment Information Packet Spring 2024.pdf">Enrollment Information Packet</a>. Then, download and complete the GT New Stud
Fall 2024

2024-04-04 20:04 UTC, petschekr commented on content/join.hbs
> +					<p>To enroll for Spring 2025, please first review the <a href="files/Enrollment Information Packet Spring 2024.pdf">Enrollment Information Packet</a>. Then, download the Crosstown New Student En
Fall 2024

2024-04-04 20:04 UTC, petschekr commented on content/join.hbs
> +			<h1>Join in <span class="semester-text">Fall 2024</span> or later</h1>
Got a duplicate line here. I think this should be Spring 2025 since it's for future interest.

2024-08-28 22:31 UTC, petschekr commented
Superseded by #72

2024-08-28 22:31 UTC, closed without merging